Repository viur-framework/viur-datastore, pull requests merged in 2022-12, with the labels that each got.

#18 Fix multiple query
  src/viur/datastore/query.py
Labels: Priority: Medium, bug

#19 Add get_orders and test
  src/viur/datastore/query.py
  src/viur/datastore/types.py
  tests/querycustomfunctions.py
Labels: Priority: Medium, enhancement

#24 fulltextsearch is broken
  src/viur/datastore/query.py
Labels: Priority: High, bug

#23 Add count for querys and db.Count
  src/viur/datastore/__init__.py
  src/viur/datastore/query.py
  src/viur/datastore/transport.pyx
  tests/basic.py
  tests/querycustomfunctions.py
Labels: Priority: Medium, enhancement
