Repository viur-framework/viur-datastore, pull requests merged in 2024-07, with the labels that each got.

#54 feat: Add requirements to `setup.py`
  setup.py
Labels: dependencies, feature

#52 feat: Implement multi Get testcases
  tests/basic.py
Labels: Priority: Low, Tests

#44 Ensure exclude_from_indexes is a set
  src/viur/datastore/types.py
Labels: Priority: Low

#55 fix: Remove indent from changes from #44
  src/viur/datastore/types.py
Labels: Priority: Critical, bug, hotfix
